services:
  sql-server-db:
    container_name: sql1
    image: mcr.microsoft.com/mssql/server:2022-CU11-ubuntu-22.04
    user: root
    # volumes:
    #   - /tmp/db/mssql:/var/opt/mssql/
    ports:
      - '127.0.0.1:1433:1433'
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Admin123456' # pragma: allowlist secret
